name: infosha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.19+27

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts:
  pinput: ^3.0.1
  # pinput:
  #  git:
  #   url: https://github.com/Tkko/Flutter_Pinput
  #   ref: dev
  
  # searchfield: ^0.6.5
  image_picker: ^1.0.2
  shared_preferences:
  provider: ^6.0.2
  
  auto_size_text:
  intl: ^0.18.1
  circular_profile_avatar: ^2.0.5
  dropdown_search: ^3.0.1
  animated_clipper: ^0.2.0+2
  
  
  animate_do: ^2.1.0
  shimmer: ^2.0.0
  custom_searchable_dropdown: ^2.1.1
  shape_of_view_null_safe: ^2.0.0
  device_info_plus:
  flash: ^3.0.5+2
  flutter_contacts: ^1.1.7+1
  firebase_crashlytics:
  characters:
  
  font_awesome_flutter:
 
  responsive_ui:
  # date_range_form_field: ^1.0.2
  cached_network_image: ^3.3.0 
  photo_view: ^0.12.0
  # splash_screen_view:
  http: ^0.13.6
  flutter_launcher_icons:
 
  intl_phone_field: ^3.2.0
  swipeable_card_stack: ^0.0.5
  flutter_image_slideshow: ^0.1.2
  dotted_border: ^2.1.0
  galleryimage:
  flutter_svg: 
  flutter_cupertino_datetime_picker: ^3.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.3
  flutter_local_notifications: ^16.2.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.6
  place_picker: 

  
  firebase_core_platform_interface: 
  
  like_button: ^2.0.5
  carousel_slider: #to slide images 
  
  jiffy: ^6.2.1
  grouped_list: ^5.1.2
  action_slider: ^0.6.1
  
  easy_image_viewer: ^1.2.0
  animated_floating_buttons: ^0.0.2
  
  permission_handler: ^10.4.5
  
  dropdown_button2: ^1.9.2 
  
  draggable_home: ^1.0.4
  connectivity_wrapper: ^1.1.1
  dropdown_textfield: ^1.0.8
  flutter_rating_bar:
  responsive_sizer: ^3.1.1
  flutter_list_view:
  coordinator_layout:
  flutter_feed_reaction: ^0.0.6
  lottie:
  expanded_bottom_sheet:
  sliding_up_panel:
  intl_phone_number_input: 0.7.3+1

  # added by us
  flutter_localization: ^0.1.14  
  url_launcher: ^6.2.2
  country_code_picker: ^3.0.0
  # mobile_number: ^2.1.1
  csc_picker:
    path: package/csc_picker
  animated_custom_dropdown:
    path: package/animated_custom_dropdown
  country_pickers: ^2.0.0
  video_player: ^2.8.2
  calendar_date_picker2: ^0.5.3
  country_state_city: ^0.1.6
  visibility_detector: ^0.4.0+2
  internet_connection_checker_plus: ^1.0.1  
  webview_flutter: ^3.0.0  
  flutter_staggered_grid_view: ^0.4.0
  share_plus: ^7.2.2
  google_mobile_ads: ^2.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  contacts_service: ^0.6.2
  flutter_overlay_window:
    path: package/flutter_overlay_window
  # flutter_overlay_window:
  #   git: 
  #     url: https://github.com/diegohzea/flutter_overlay_window.git
  #     ref: main

  flutter_background_service: ^5.0.6
  phone_state: ^1.0.3 
  system_alert_window:
    path: package/system_alert_window  
  flutter_deep_linking: ^0.2.1
  uni_links: ^0.5.1
  fluttertoast: ^8.2.5    

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/flags/
    - assets/emojies/
    - assets/lottie/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
