// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiwiHNZsx3SqJTMtVx0fwz_mpFDlruZ88',
    appId: '1:783570328741:web:1b9a263cc6d2af0e02c14c',
    messagingSenderId: '783570328741',
    projectId: 'infosha-c3967',
    authDomain: 'infosha-c3967.firebaseapp.com',
    storageBucket: 'infosha-c3967.appspot.com',
    measurementId: 'G-7DZKDV9K2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9dknrhC2kcUgeU6X3vqMn40OVCkBpKAg',
    appId: '1:783570328741:android:86c369d10285a20f02c14c',
    messagingSenderId: '783570328741',
    projectId: 'infosha-c3967',
    storageBucket: 'infosha-c3967.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLeuAQYYwOUK3TBT9kzxAZp4RwTCUiZEg',
    appId: '1:783570328741:ios:31e5bce563ae2efe02c14c',
    messagingSenderId: '783570328741',
    projectId: 'infosha-c3967',
    storageBucket: 'infosha-c3967.appspot.com',
    iosBundleId: 'com.ktech.infosha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLeuAQYYwOUK3TBT9kzxAZp4RwTCUiZEg',
    appId: '1:783570328741:ios:31e5bce563ae2efe02c14c',
    messagingSenderId: '783570328741',
    projectId: 'infosha-c3967',
    storageBucket: 'infosha-c3967.appspot.com',
    iosBundleId: 'com.ktech.infosha',
  );
}
